# GitHub Linguist configuration
# This file tells GitHub how to analyze the repository for language statistics

# Exclude these from language analysis
exclude:
  - docs/.vuepress/dist
  - docs/.vuepress/.cache
  - docs/.vuepress/.temp
  - node_modules
  - "*.min.js"
  - "*.min.css"
  - "*.log"
  - package-lock.json
  - "index.html.vue"
  - "404.html.vue"
  - "style-*.css"
  - "articleTagColors.css"
  - "iconify.css"

# Force language detection for specific files
# This ensures Vue and CSS files are properly recognized

# Include all source code files
include:
  - "*.ts"
  - "*.vue"
  - "*.css"
  - "*.js" 