# GitHub Linguist configuration
# This file tells GitHub how to analyze the repository for language statistics

# Exclude these from language analysis
exclude:
  - docs/.vuepress/dist
  - docs/.vuepress/.cache
  - docs/.vuepress/.temp
  - node_modules
  - "*.min.js"
  - "*.min.css"
  - "*.log"
  - package-lock.json 